name: Deploy Mood App

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '22'

    - name: Install dependencies
      run: npm install

    - name: Build project
      run: npm run build

    - name: Add SSH Key
      uses: webfactory/ssh-agent@v0.7.0
      with:
        ssh-private-key: ${{ secrets.VPS_PRIVATE_KEY }}

    - name: Test SSH Connection
      run: |
        echo "Testing SSH connection to VPS..."
        ssh -vvv -o StrictHostKeyChecking=no -p ${{ secrets.VPS_PORT }} root@${{ secrets.VPS_HOST }} "echo 'SSH connection successful'"
        if [ $? -ne 0 ]; then
          echo "SSH connection failed"
          exit 1
        fi
        echo "SSH connection successful"

    - name: Copy files via SSH
      run: |
        echo "Starting rsync..."
        rsync -avz -e "ssh -vvv -o StrictHostKeyChecking=no -p ${{ secrets.VPS_PORT }}" ./ root@${{ secrets.VPS_HOST }}:/home/mood-app/
        if [ $? -ne 0 ]; then
          echo "rsync failed"
          exit 1
        fi
        echo "rsync completed."

    - name: Restart application via SSH
      run: |
        echo "Connecting to server to restart application..."
        ssh -vvv -o StrictHostKeyChecking=no -p ${{ secrets.VPS_PORT }} root@${{ secrets.VPS_HOST }} << 'EOF'
          echo "Navigating to application directory..."
          cd /home/mood-app
          if [ $? -ne 0 ]; then
            echo "Failed to change directory"
            exit 1
          fi
          echo "Installing production dependencies..."
          npm install --production
          if [ $? -ne 0 ]; then
            echo "npm install failed"
            exit 1
          fi
          echo "Restarting application using pm2..."
          pm2 restart all || pm2 start npm --name "mood-app" -- start
          if [ $? -ne 0 ];then
            echo "pm2 restart failed"
            exit 1
          fi
          echo "Application restarted."
        EOF
        if [ $? -ne 0 ]; then
          echo "SSH command failed"
          exit 1
        fi
        echo "SSH command completed."

